

### Base url
GET https://devapi.smartportgms.com/
### 1
GET https://devapi.smartportgms.com/tourney

### 2
GET https://devapi.smartportgms.com/dates/juegos

### 3
GET https://devapi.smartportgms.com/juegos?&sort=date&order=1&tourney=femmfx-2024

### 4
GET https://devapi.smartportgms.com/tablePosition/femmfx-2024

### 5
GET https://devapi.smartportgms.com/person?_id[]=66eb4527b4ad843252126aa2&_id[]=66eb4bb47fb57b119d6d9b62&_id[]=66f07aafa786fb25f5641e82&_id[]=66f214ac6cd1f53ae737c8f2&_id[]=6705a5e09e79c023a9743022&_id[]=66eb4cbe946ba81fa62408f2&_id[]=66eb42dda617c644334f7c82&_id[]=66eb441f8584776a09020982&_id[]=6705d43543b02b5102688fc2&_id[]=6705a4f366ff917ef51be722&_id[]=6705d56343b02b5102688fc3&_id[]=66eb4e8769750e68fe4cea52&_id[]=66eb49c2a6acab1a843eb3e2&_id[]=66b087a1b6c99ebf3eb2f785&_id[]=capitan&_id[]=66b087a0b6c99ebf3eb2f5bc&_id[]=66b087a0b6c99ebf3eb2f61d&_id[]=66b087a1b6c99ebf3eb2f901&_id[]=66b087a0b6c99ebf3eb2f5bb&_id[]=66b087a0b6c99ebf3eb2f5b4&_id[]=66b087a0b6c99ebf3eb2f5b1false

### 5 . 1
GET https://devapi.smartportgms.com/img/person/thumb/7504b41c9515d8823c6e34be4a67e145.jpg

### 5 . 2
GET https://devapi.smartportgms.com/person?_id[]=66e4fd79f0972857dd48dfb2

### 6
GET https://devapi.smartportgms.com/users?delegation=true

### 7
GET https://devapi.smartportgms.com/juegos/66f94c16569c9176320e3e83

### 8
GET https://apic13.smartportgms.com/sedes?name=LICEO APLICACIÓN

### 9
GET https://devapi.smartportgms.com/inscriptions?tourney_alias=femmfx-2024&alias[]=ECL-A&alias[]=FUN-A


### 10 
GET https://devapi.smartportgms.com/inscriptions?delegation=ECR



### 11 
GET https://devapi.smartportgms.com/person/records/66f4a60661c69c3c212ac9a2

### 12 
GET https://devapi.smartportgms.com/light/tourney?active=true&sort=date&order=1


### 13 
GET https://devapi.smartportgms.com/juegos?roster.66f607af12ed676c934f2f02.dorsal[$exist]=true


### 14 
GET https://devapi.smartportgms.com/juegos?roster.66f607af12ed676c934f2f02.dorsal[$ne]=true

### 15
GET https://devapi.smartportgms.com/person/records/66b087a1b6c99ebf3eb2f840

### 16
GET https://devapi.smartportgms.com/juegos?delegation=BFC&tourney[]=feppix-2024&tourney[]=faiicx-2024

### 17
GET https://devapi.smartportgms.com/event?ev=cvg


### 18
GET https://apic13.smartportgms.com/tourney/records/fds-sub-13-unica-mixto-2025



### mextapi  1
GET http://localhost:3000/api/tablePosition/femmfx-2024

### mextapi  2
GET http://localhost:3000/api/roster/66dde7d84a27284bf04b3cc2/66ddd953e1327016150677f2/66f3981df5ee1f7a492e1152/66e8784aa8197936813f0242/66dde6b3024e01370a680ec2/66e8ac01f78dd65a197288c3/66f48ee3cf8da836101085f4/66f395f6114abe457540c2d3/66f48798cf8da836101085f2/66ddd7c8c4781f24a5655632/66f55bc445e5d02fda6d9832/66f21d4ccf3c4f5e646c4e82

### mextapi  juegos
GET http://localhost:3000/api/search/games/BFC/asofutsal/10/0

### mextapi  perosnas
GET http://localhost:3000/api/search/persons/BFC/asofutsal/10/20

### mextapi  qqqqqq
GET https://devapi.smartportgms.com/person?search=juan&ev=asofutsal&limit=10&skip=0

### ffff
GET https://devapi.smartportgms.com/tablePosition/fds-infantil-a-unica-female?ev=infa

